// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteAlbum(arg1:number):Promise<void>;

export function ImportAlbum(arg1:Array<string>,arg2:string,arg3:string,arg4:string):Promise<models.Vinyl>;

export function MarkVinylPlayed(arg1:number):Promise<void>;
