// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAlbum(arg1) {
  return window['go']['services']['ImportService']['DeleteAlbum'](arg1);
}

export function ImportAlbum(arg1, arg2, arg3, arg4) {
  return window['go']['services']['ImportService']['ImportAlbum'](arg1, arg2, arg3, arg4);
}

export function MarkVinylPlayed(arg1) {
  return window['go']['services']['ImportService']['MarkVinylPlayed'](arg1);
}
