// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllVinyls() {
  return window['go']['services']['LibraryService']['GetAllVinyls']();
}

export function UpdateVinyl(arg1, arg2, arg3, arg4) {
  return window['go']['services']['LibraryService']['UpdateVinyl'](arg1, arg2, arg3, arg4);
}
