// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetAllVinyls():Promise<Array<models.Vinyl>>;

export function UpdateVinyl(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;
