// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAudioFileURL(arg1:string):Promise<string>;

export function GetImageFileURL(arg1:string):Promise<string>;

export function SelectAudioFiles():Promise<Array<string>>;

export function SelectImageFile():Promise<string>;
