// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAudioFileURL(arg1) {
  return window['go']['main']['App']['GetAudioFileURL'](arg1);
}

export function GetImageFileURL(arg1) {
  return window['go']['main']['App']['GetImageFileURL'](arg1);
}

export function SelectAudioFiles() {
  return window['go']['main']['App']['SelectAudioFiles']();
}

export function SelectImageFile() {
  return window['go']['main']['App']['SelectImageFile']();
}
